config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  scope format: :json do
    mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
      registrations: 'api/v1/registrations',
      sessions: 'api/v1/sessions',
      passwords: 'api/v1/passwords'
    }
  end

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      get :status, to: 'health#status'
      resources :impersonations, only: %i[create], constraints: Impersonation::EnabledConstraint.new
      devise_scope :user do
        resource :user, only: %i[update show]
      end
      resources :settings, only: [] do
        get :must_update, on: :collection
      end
    end
  end

  resource :cart, only: :show

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    authenticate(:admin_user) do
      mount Flipper::UI.app(Flipper) => '/feature-flags'
    end
  end

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?
end

app/views/navbar/_header_navigation.html.erb
<nav class="bg-black flex items-center justify-between md:p-[25px_119px_25px_119px] p-[16px] gap-[96px] mx-auto">
  <a href="<%= root_path %>">
    <%= image_tag("bm-logo.svg") %>
  </a>

  <a href="<%= cart_path %>" class="border border-white rounded-[8px] text-white flex items-center px-[9px] py-[9px] gap-[16px]">
    <span class="text-[14px] hidden md:inline">Shopping Cart</span>
    <%= image_tag("cart-icon.svg") %>
  </a>
</nav>